# port 설정
server:
  port: 9000 

# mysql setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#   h04ju <- 강사님꺼 bit!@#123
#    url: jdbc:mysql://db-h04ju-kr.vpc-pub-cdb.ntruss.com:3306/studydb?serverTimezone=Asia/Seoul
    url: jdbc:mysql://db-g66mq-kr.vpc-pub-cdb.ntruss.com:3306/bit701?serverTimezone=Asia/Seoul
    username: study
    password: bit123!@#
  servlet:
    multipart:
      max-file-size: 20MB
# swagger 설정 (boot 2.6 이후에만 추가)
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
        
    
#mybatis
mybatis:
  type-aliases-package: data.dto
  mapper-locations:
  - /mapper/**/*.xml
  
